---

- name: Manage Paths
  block:

    - name: Ensure Galaxy version is set
      include_tasks: _inc_galaxy_version.yml
      when: __galaxy_major_version is undefined

    - name: Deploy Galaxy Unit
      template:
        # owner: "{{ galaxy_systemd_root | ternary('root', omit) }}"
        # group: "{{ galaxy_systemd_root | ternary('root', omit) }}"
        owner: "{{ galaxy_systemd_root | ternary('root', __galaxy_user_name) }}"
        group: "{{ galaxy_systemd_root | ternary('root', __galaxy_user_group) }}"
        mode: 0644
        src: systemd/galaxy.service.j2
        ## the directory /home/ec-galaxy/.config/systemd/user must be created manually!!!
        dest: "{{ galaxy_systemd_root | ternary('/etc/systemd/system/', ('~' ~ __galaxy_user_name ~ '/.config/systemd/user') | expanduser) }}/galaxy.service"
      notify:
        - systemd daemon reload
        - start galaxy
        - restart galaxy

    - name: Enable Galaxy service unit
      systemd:
        name: galaxy.service
        enabled: yes
        scope: "{{ galaxy_systemd_root | ternary(omit, 'user') }}"
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ galaxy_user.uid }}"


  # remote_user: "{{ galaxy_remote_users.root | default(__galaxy_remote_user) }}"
  # become: "{{ true if galaxy_become_users.root is defined else __galaxy_become }}"
  # become_user: "{{ galaxy_become_users.root | default(__galaxy_become_user) }}"
  become_user: "{{ __galaxy_user_name }}"

